[package]
name = "rusty-atlas"
version = "0.1.0"
authors = ["NPCRUS <npcrus@gmail.com>", "lylz <rnationtech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
image = "0.23.14"
